baseURL = "https://jeevamichael.github.io/"
title = "ENMIN"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "ENMIN DIGITAL SOLUTIONS" # title for frontpage, may include image
img = "/img/enmin_wlogo.png"
copyright = "Enmin Digital Solutions"
#description = 'Digital transformation in a nutshell<br />crafted by <a href="http://html5up.net">HTML5 UP</a>.<br />Ported to <a href="//gohugo.io">Hugo</a> by Simon Bruder.'
description = 'Digital transformation in a nutshell<br />'
startbuttonText = "Activate"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'ABOUT US'
body = '''
Enmin was founded as a result of our pursuit to guide industries towards digital transformation. We help our clients to grow their business and reduce operational costs in a rapidly changing business environment. Enmin provides the skills and solutions needed to improve the quality of your businesses with the minimal digital footprint possible, thereby saving costs as well as planet earth.
'''

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/pexels-fauxels-3183197.jpg"
title = 'WHAT WE OFFER<br />'
body = 'We can guide you on your journey towards digital transformation by providing services such as consultation, development and testing of various digital solutions. We empower your business to become self-sufficient by training your resources. We can review your existing processes, provide both preventive and corrective action plan, recommend areas to improve and guide you to implement an efficient overall process. Our tech-savvy enthusiasts can help you navigate the challenges involved and deliver quality products quicker.'

[[params.two.section]]
img = "img/pexels-fauxels-3182765.jpg"
title = 'WHAT WE STAND FOR<br />'
body = 'At Enmin, we put people first in everything we do. We respect each other and draw strength from our differences. We stand for women empowerment, equality and love. We want to make the environment greener and minimise digital waste.'

[[params.two.section]]
img = "img/pexels-andrea-piacquadio-3771097.jpg"
title = 'Benefits of working with ENMIN <br />'
body = 'On the rapidly changing IT every day, we are passionate about our client success. We conduct our business with high ethical standards. We Protect your valuable information and brand reputation. We believe performance is an asset. We put your business improvement at the heart of all we do. At Enmin, you will always find the right solution for your needs and achieve the best possible result.'

[params.three]
enable = true
title = 'OUR SERVICES'
#body = '''
#Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
#fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
#'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Software Development services"
body = "Application development is complex and dynamic. We build sophisticated business applications that withstand the fast-changing technology. Our team makes sure that your app is multi-tenant, secure and robust. Our practice specializes in application services that span the full software development life cycle"

[[params.three.feature]]
icon = "fa-laptop"
title = "Software Testing Services"
body = "Enmin will help you prepare for the unpredictable. Our end- to- end approach makes sure your product ticks all the checkboxes when it comes to quality, usability and reliability. Our testing team ensures your product meet business and customer demands across functionality, compatibility, usability and reliability."

[[params.three.feature]]
icon = "fa-code"
title = "Consultation Services"
body = "We offer advices on our clients most critical issues. Our team coaches you through every tech decision critical to you. We can build a better digital-world together."

[[params.three.feature]]
icon = "fa-headphones"
title = "Maintenance"
body = "We don’t walk off after your new software solution is up and running. We are here for the entire journey. We assure you we will be on hand for post-deployment technical support and solve any minor problems that can pop up time to time."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Updates"
body = "We make updates a seamless process. We are here for any updates that your product needs as and when required. "

[[params.three.feature]]
icon = "fa-flag-o"
title = "Digital Marketing"
body = "We are passionate tech people who think out of the box. We offer advices on how to manage your online presence and build reliable marketing assets using digital marketing."

[params.cta]
enable = true
title = "Let's Collaborate"
body = "You understand your business better than anyone, which is why the work we do with our clients is collaborative. Let’s join and multiply the success."

#[[params.cta.link]]
#href = "#"
#text = "Activate"
#special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
